# Generated by Django 5.1.4 on 2024-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('ingredient_type', models.CharField(max_length=50)),
                ('stock_in_date', models.DateField(blank=True, null=True)),
                ('stock_in_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
