# Generated by Django 5.1.4 on 2024-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
