# Generated by Django 5.1.4 on 2024-12-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_stock_out_date_product_stock_out_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
